services:
  api:
    container_name: rest_api
    build: 
      context: .
      dockerfile: ./build/rest-server/Dockerfile
    ports:
      - "8080:8080"
    command: ./bin/filmoteka -env ./docker.env 
    environment:
      DATABASE_HOST: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filmoteka
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  db_data: {}
  es_data: {}
